#!/bin/bash

function usage(){
  echo -e "error\ncurrect usage: \n./problem (name) -l (lang)"
}

function openFile(){ #file
  if test ".problemconfig"; then
    file=$(<".problemconfig")
    re='defaultapp: ([^:]*):'
    if [[ $file =~ $re ]]; then
      open -a"${BASH_REMATCH[1]}" $1
      exit 0
    else
      echo "fnf in .problemconfig"
      exit 1
    fi
  else
    echo "missing .problemconfig"
    exit 1
  fi
}

function writeFile(){ #folder #language
  if test ".problemconfig"; then
    re="$2: ([^ ]+) ([^:]*):"
    file=$(<".problemconfig")
    if [[ $file =~ $re ]]; then
      mkdir "$1"
      touch "$1/${BASH_REMATCH[1]}"
      echo "${BASH_REMATCH[2]}" > "$1/${BASH_REMATCH[1]}"
      openFile "$1/${BASH_REMATCH[1]}"
      exit 0
    else
      echo "fnf in .problemconfig"
      exit 1
    fi

  else
    echo "missing .problemconfig"
    exit 1
  fi
}

if [ $# -eq 1 ]; then
  mkdir $1
  exit 0
fi

if [ $# -eq 3 ]; then
  if [ $2 == "-l" ]; then
    writeFile "$1" "$3"
  fi
  echo -e "$(usage)"
  exit 1
fi

echo -e "$(usage)"
exit 1
