#!/bin/bash

function usage(){
  echo -e "error\ncurrect usage: \n./problem (name) -l (lang)"
}

if [ $# -eq 1 ]; then
  mkdir $1
  exit 0
fi

if [ $# -eq 3 ]; then
  if [ $2 == "-l" ]; then
    mkdir $1
    #touch "$1/main.$3"
    #if [ $3 == "cpp" ]; then
      #touch "$1/makefile"
      #echo -e "bin: main.cpp\n\tg++ -std=c++11 -Wall -Wextra -pedantic -O2 -o bin main.cpp" >> "$1/makefile"
    #fi
    #exit 0

    case $3 in

      cpp)
      touch "$1/makefile"
      touch "$1/main.cpp"
      echo -e "bin: main.cpp\n\tg++ -std=c++11 -Wall -Wextra -pedantic -O2 -o bin main.cpp" >> "$1/makefile"
      echo -e "#include <iostream>\n\nint main(){\n\treturn 0;\n}" >> "$1/main.cpp"
      exit 0
      ;;

      py)
      touch "$1/main.py"
      exit 0
      ;;

      java)
      touch "$1/Main.java"
      echo -e "public class Main{\n\t\n}" >> "$1/Main.java"
      exit 0
      ;;

      *)
      echo -e"$(usage)"
      exit 1
      ;;
    esac
  fi
  echo -e "$(usage)"
  exit 1
fi

echo -e "$(usage)"
exit 1
